"""empty message

Revision ID: 03246d069c4f
Revises: 
Create Date: 2021-05-09 18:20:34.934471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03246d069c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('identifier', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('account_type', sa.Enum('Ahorro', 'Corriente', name='type_account'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id', 'client_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('account_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('reciever_account_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('account_transaction_type', sa.Enum('P2P', 'P2B', name='transaction_type'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('details', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['reciever_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id', 'sender_account_id', 'reciever_account_id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_transaction')
    op.drop_table('account')
    op.drop_table('client')
    # ### end Alembic commands ###
