"""empty message

Revision ID: 82848721d187
Revises: 9e8918f0f3e2
Create Date: 2021-04-25 18:51:45.099359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82848721d187'
down_revision = '9e8918f0f3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('reciever_account_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=10), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('account_transaction_type', sa.Enum('P2P', 'P2B'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('details', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['reciever_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id', 'sender_account_id', 'reciever_account_id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_transaction')
    # ### end Alembic commands ###
